version: '3'

services:
  nginx:
    build: ./docker/nginx/
    restart: unless-stopped
    volumes:
      - ./:/var/www/project:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    ports:
      - "8001:80"
      - "8080:8080"
    depends_on:
      - php
    networks:
      - app-network
  php:
    build: ./docker/php/
    restart: unless-stopped
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://root:goose@mysql:3306/project?serverVersion=5.7
    volumes:
      - ./:/var/www/project:delegated
    depends_on:
      - mysql
    networks:
      - app-network
  mysql:
    image: mysql:8.0.21
    #build: ./docker/database/
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: goose
      MYSQL_PASSWORD: goose
      MYSQL_DATABASE: project
      MYSQL_USER: niels
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql/:delegated
      - ./docker/database/mysqld.cnf:/etc/mysql/my.cnf:delegated
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local